### ISSUE TITLE
Test `bsv-donotcheck-relay-collision.py`  failed

### ISSUE THREAD

**Issue by Ljzn** [bitcoin-sv/bitcoin-sv#279]
### Describe the issue

Test `bsv-donotcheck-relay-collision.py`  failed.

#### If so, please list the steps to reproduce below:

configure with these labels:
```
configure --enable-wallet --with-utils --with-daemon --disable-bench --enable-reduce-exports --disable-tests --prefix=`pwd`/depends/aarch64-linux-gnu
```

after compiled, run test with `./test/functional/test_runner.py`

### Expected behaviour

no failed test

### Actual behaviour

test failed

### Screenshots.

```
bsv-donotcheck-relay-collision.py failed, Duration: 63 s

stdout:
2022-09-11 04:58:36.002000 TestFramework (INFO): Initializing test directory /tmp/bitcoin_test_runner_20220911_045247/bsv-donotcheck-relay-collision_321
2022-09-11 04:58:36.841000 TestFramework.mininode (INFO): Connecting to Bitcoin Node: 127.0.0.1:13568
2022-09-11 04:59:37.194000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/runner/work/bitcoin-sv/bitcoin-sv/test/functional/test_framework/test_framework.py", line 137, in main
    self.run_test()
  File "/home/runner/work/bitcoin-sv/bitcoin-sv/build/../test/functional/bsv-donotcheck-relay-collision.py", line 116, in run_test
    assert(allInvsMatch(txnids[dummy_index + 1:], test_node))
AssertionError
2022-09-11 04:59:37.19[500](https://github.com/Ljzn/bitcoin-sv/runs/8289572025?check_suite_focus=true#step:10:501)0 TestFramework (INFO): Stopping nodes
2022-09-11 04:59:39.304000 TestFramework (WARNING): Not cleaning up dir /tmp/bitcoin_test_runner_20220911_045247/bsv-donotcheck-relay-collision_321
2022-09-11 04:59:39.304000 TestFramework (ERROR): Test failed. Test logging available at /tmp/bitcoin_test_runner_20220911_045247/bsv-donotcheck-relay-collision_321/test_framework.log
2022-09-11 04:59:39.305000 TestFramework (ERROR): Hint: Call /home/runner/work/bitcoin-sv/bitcoin-sv/test/functional/combine_logs.py '/tmp/bitcoin_test_runner_20220911_045247/bsv-donotcheck-relay-collision_321' to consolidate all logs
```

### What version of bitcoin-sv are you using?

v1.0.11

### Machine specs:
- OS: ubuntu 20.04

**Comment by Ljzn** [comment]
Can't reproduce, may be just an accident.
